using System.Runtime.InteropServices;

namespace Activator.Enums
{
    /// <summary>
    ///     The HARDWAREINPUT structure contains information about a simulated message generated by an input device other than
    ///     a keyboard or mouse. (see: http://msdn.microsoft.com/en-us/library/ms646269(VS.85).aspx) Declared in Winuser.h,
    ///     include Windows.h
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal struct HARDWAREINPUT
    {
        public uint Msg;
        public ushort ParamL;
        public ushort ParamH;
    }
}